# Generated by Django 5.2.7 on 2025-10-27 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarquia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título da Vaga/Cargo')),
                ('centro_custo', models.CharField(blank=True, max_length=100, verbose_name='Centro de Custo')),
                ('tipo_contratacao', models.CharField(choices=[('clt', 'CLT'), ('pj', 'PJ'), ('estagio', 'Estágio'), ('temporario', 'Temporário'), ('terceiro', 'Terceiro')], default='clt', max_length=20, verbose_name='Tipo de Contratação')),
                ('faixa_salarial_inicial', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Faixa Salarial (Início)')),
                ('faixa_salarial_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Faixa Salarial (Fim)')),
                ('requisitos_tecnicos', models.TextField(blank=True, verbose_name='Competências Técnicas')),
                ('requisitos_comportamentais', models.TextField(blank=True, verbose_name='Competências Comportamentais')),
                ('principais_atividades', models.TextField(blank=True, verbose_name='Principais Responsabilidades/Atividades')),
                ('formacao_academica', models.TextField(blank=True, verbose_name='Formação Acadêmica')),
                ('beneficios', models.TextField(blank=True, verbose_name='Benefícios')),
                ('justificativa', models.TextField(verbose_name='Justificativa da Vaga (RH/DP)')),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('em_processo', 'Em Processo de Seleção'), ('congelada', 'Congelada'), ('fechada', 'Fechada')], default='aberta', max_length=20, verbose_name='Status da Vaga')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vagas', to='hierarquia.cargo', verbose_name='Cargo da Vaga')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vagas_criadas', to='hierarquia.funcionario', verbose_name='Criado Por (RH/DP)')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vagas', to='hierarquia.setor', verbose_name='Setor da Vaga')),
            ],
            options={
                'verbose_name': 'Vaga',
                'verbose_name_plural': 'Vagas',
            },
        ),
        migrations.CreateModel(
            name='RequisicaoPessoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Abertura')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tipo_vaga', models.CharField(choices=[('nova', 'Nova Posição'), ('substituicao', 'Substituição')], default='nova', max_length=20, verbose_name='Tipo de Vaga')),
                ('nome_substituido', models.CharField(blank=True, help_text='Preencher se for Substituição.', max_length=200, null=True, verbose_name='Nome do Substituído')),
                ('motivo_substituicao', models.CharField(blank=True, choices=[('demissao', 'Demissão'), ('promocao', 'Promoção'), ('transferencia', 'Transferência'), ('aposentadoria', 'Aposentadoria'), ('termino_contrato', 'Término de Contrato'), ('outro', 'Outro')], max_length=30, null=True, verbose_name='Motivo da Substituição')),
                ('local_trabalho', models.CharField(blank=True, max_length=200, verbose_name='Local de Trabalho')),
                ('data_prevista_inicio', models.DateField(blank=True, null=True, verbose_name='Data Prevista para Início')),
                ('prazo_contratacao', models.DateField(blank=True, null=True, verbose_name='Prazo Limite para Contratação')),
                ('horario_trabalho', models.CharField(blank=True, max_length=100, verbose_name='Horário de Trabalho')),
                ('justificativa_rp', models.TextField(help_text='Descreva a necessidade desta contratação.', verbose_name='Justificativa da Contratação')),
                ('status', models.CharField(choices=[('pendente_nivel_4', 'Pendente Supervisor'), ('pendente_nivel_3', 'Pendente Coordenador'), ('pendente_nivel_2', 'Pendente Gerente'), ('pendente_nivel_1', 'Pendente Diretor'), ('aprovada', 'Aprovada (RH)'), ('rejeitada', 'Rejeitada'), ('cancelada', 'Cancelada')], max_length=30, verbose_name='Status da Requisição')),
                ('observacoes_aprovador', models.TextField(blank=True, verbose_name='Observações do Aprovador')),
                ('data_aprovacao_supervisor', models.DateTimeField(blank=True, null=True)),
                ('data_aprovacao_coordenador', models.DateTimeField(blank=True, null=True)),
                ('data_aprovacao_gerente', models.DateTimeField(blank=True, null=True)),
                ('data_aprovacao_diretor', models.DateTimeField(blank=True, null=True)),
                ('data_rejeicao', models.DateTimeField(blank=True, null=True)),
                ('aprovado_por_coordenador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='hierarquia.funcionario')),
                ('aprovado_por_diretor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='hierarquia.funcionario')),
                ('aprovado_por_gerente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='hierarquia.funcionario')),
                ('aprovado_por_supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='hierarquia.funcionario')),
                ('aprovador_atual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rps_para_aprovar', to='hierarquia.funcionario', verbose_name='Próximo Aprovador')),
                ('rejeitado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='hierarquia.funcionario')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rps_solicitadas', to='hierarquia.funcionario', verbose_name='Solicitante')),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisicoes', to='hierarquia.vaga', verbose_name='Vaga Solicitada')),
            ],
            options={
                'verbose_name': 'Requisição Pessoal',
                'verbose_name_plural': 'Requisições Pessoais',
                'ordering': ['-criado_em'],
            },
        ),
    ]
