# Generated by Django 5.2.7 on 2025-10-20 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarquia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='setor',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='setor',
            field=models.ManyToManyField(related_name='funcionarios', to='hierarquia.setor'),
        ),
    ]
