# Generated by Django 5.2.7 on 2025-10-31 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarquia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_adcinte',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_adfer',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_adianta',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_admissa',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_afastad',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_agencia',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_agencpa',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_agpis',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_alfabet',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_altcbo',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_altdata',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_alter',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_altqdr',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_anocheg',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_anofreq',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_apvdesc',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_assmed',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_avsopag',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_banco',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_bancopi',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_bancpa',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_barra',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_bcafas',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_bdi',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_bens',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_cartmot',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_catfgts',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_catfunc',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_cathab',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_catind',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_catmed',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_catprev',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_catres',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_catseg',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_catsind',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_caudem',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_cbo',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_cbocod',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_cc',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_celula',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_certres',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_cgcfav',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_chapa',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_cic',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_cidade',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_classec',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_clfunc',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_cnhdtve',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_codafas',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_codarea',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_codfil',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_codfor',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_codfunc',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_codlot',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_codmed',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_codmova',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_codmuni',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_codmunic',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_codpais',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_codposto',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_codprev',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_codraca',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_codseg',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_codsind',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_codtab',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_codunid',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_coduser',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_complem',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_conjug',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_conta',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_contapa',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_contfg',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_contrpr',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_contrpr2',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_ctdp',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_ctdtem',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_datafim',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_dataini',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_ddd',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_defiau',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_defifa',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_defifi',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_defime',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_defimo',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_defivi',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_demissa',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_descont',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_diacest',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_diaprid',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_diasafa',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_digag',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_digapa',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_digcpa',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_digcta',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_dmedant',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_dpc',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_dtabspg',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_dtafas',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_dtafast',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_dtalcf',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_dtcadpi',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_dtcp',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_dtdesl',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_dtexam',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_dtexcl',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_dtexprg',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_dtexpv',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_dtexpv2',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_dtfgts',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_dtfimpen',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_dtinic',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_dtinicarg',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_dtinpen',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_dtnasc',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_dtpag',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_dtransf',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_dtreadm',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_dtreaf',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_dtrecon',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_dtregpr',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_dtvencv',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_email',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_endpis',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_estabil',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_estcivi',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_faixa',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_faltas',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_favorec',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_ferlim',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_ferprep',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_ferprot',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_fervcta',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_fervctb',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_fervenc',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_fgrlim',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_fgrprep',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_fgrprot',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_fgrvcta',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_fgrvctb',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_fgts',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_filant',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_filhom',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_filhomai',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_flimes',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_formpgt',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_foto',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_fprepes',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_fprotes',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_fvctaes',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_fvctbes',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_grinst',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_habven',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_hisalul',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_histalt',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_horario',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_hrsdia',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_hrsmes',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_hrssem',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_inativo',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_instruc',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_logra',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_loja',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_matant',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_matfunc',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_matmed',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_matprev',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_matseg',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_memcalc',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_mudou',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_munic',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_nacioc',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_naciona',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_nascfav',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_natural',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_nfilhos',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_nivfunc',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_nivsal',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_nmedica',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_nmovi',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_nomemae',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_nomepai',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_numcart',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_numcp',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_numdias',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_numero',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_numprocesso',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_numres',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_numvtic',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_obsmot',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_opsindic',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_orgemrg',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_orgreg',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_origem',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_outdef',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_pag13',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_pensao',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_peradit',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_perinsa',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_perpens',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_perper',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_perref',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_plubs',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_pontac',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_postatu',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_prevpri',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_process',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_prodtet',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_prorrog',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_provim',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_readmis',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_reccesta',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_recfer',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_recpror',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_refeic',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_refrh',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_regmtr',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_regprof',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_resbai',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_rescep',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_rescomp',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_resddd',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_reservi',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_reslog',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_resmunic',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_restel',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_resuf',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_rhdata',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_rhhora',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_rhmata',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_salario',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_saldabj',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_saldabn',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_saldfej',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_saldfer',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_saldlic',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_sbase',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_secao',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_segvid',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_sercp',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_sindica',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_situaca',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_sreser',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_suecia',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_tabrub',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_telefon',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_tipo',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_tipoadm',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_tipocel',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_tipoconta',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_tipocor',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_tipofav',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_tipopas',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_tipopgt',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_tipoprf',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_tipores',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_tipovst',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_tippla',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_titular',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_tnotrab',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_tppens',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_tpper',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_tpvinc',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_ufcp',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_ufnatu',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_ufrg',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_ultcal',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_ultfech',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_ultnasc',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_usufluig',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_valadds',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_valeped',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_valet',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_valetrf',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_valmed',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_valprev',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_valseg',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_vbmed',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_vbseg',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_vendfer',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_viemrai',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_vincemp',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_vlpens',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_vlrbase',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_vlref',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ra_zonasec',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_acumbhoras',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Acum.B.Horas'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_adcconf',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='% Adc.Conf.'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_adctmpserv',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Adc.Tmp.Serv'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_adctrf',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='%Adc.Trf.'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_adiantam',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='% Adiantam.'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_alojado',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Alojado'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_alt_cbo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Alt. CBO'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_altadmissao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Alt.Admissao'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_altcarprof',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Alt.Car.Prof'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_altdt_nasc',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Alt.Dt. Nasc'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_alterou_end',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Alterou End.'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_altnome',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Alt.Nome'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_altopçao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Alt.Opçao'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_altpis',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Alt.PIS'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_ano_chegada',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ano Chegada'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_apelido',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Apelido'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_aposentado',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Aposentado'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_bcoag_fgts',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bco.Ag. FGTS'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_bcoagdsal',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bco.Ag.D.Sal'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_bh_p_folh',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='B.H. p/ Folh'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_bloq_admis',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bloq. Admis.'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_branascext',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bra.Nasc.Ext'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_brpdh',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='BR/PDH'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_c_nacion_rfb',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='C Nacion RFB'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_c_sindicato',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='C. Sindicato'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_caixa_postal',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Caixa Postal'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_calc_inss',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Calc. INSS'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_cargo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cargo'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_carthabil',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cart.Habil.'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_cartprofis',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cart.Profis.'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_cartório',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cartório'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_casado_bras',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Casado Bras.'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_cat_esocial',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cat. eSocial'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_cat_func',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cat. Func.'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_categ_sefip',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Categ. SEFIP'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_cdinstrais',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cd.Inst.RAIS'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_cdpais_emis',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cd.Pais Emis'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_cdrescrais',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cd.Resc.RAIS'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_centro_custo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Centro Custo'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_cep_cpostal',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CEP C.Postal'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_citar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CItar'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_class_estra',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Class. Estra'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_classe_valor',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Classe Valor'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_clau_assec',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Clau. Assec.'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_cnh_categ',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CNH Categ.'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_cnh_dt_val',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CNH Dt Val'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_cnh_dtemis',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CNH DtEmis'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_cnh_emissor',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CNH Emissor'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_cnh_uf',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CNH UF'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_cod_chapa',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cod. Chapa.'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_cod_depto',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cod. Depto.'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_cod_funcao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cod. Funcao'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_cod_funcion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cod. Funcion'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_cod_mun_nasc',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cod Mun Nasc'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_cod_municip',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cod Municip'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_cod_posto',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cod. Posto'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_cod_processo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cod Processo'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_cod_profiss',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cod Profiss'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_codafafgts',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cod.Afa.FGTS'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_codmun_ric',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cod.Mun. RIC'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_codmuncert',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cod.Mun.Cert'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_codpais_ori',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cod.Pais Ori'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_codretencao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cod.Retencao'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_comp_sábado',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Comp. Sábado'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_complem_rg',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Complem. RG'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_complender',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Compl.Ender.'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_contr_assis',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Contr. Assis'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_contr_confed',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Contr Confed'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_cota_def',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cota Def'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_cpf',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_ctadepfgts',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cta.Dep.FGTS'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_ctadepsal',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cta.Dep.Sal.'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_ctr_mat_tsv',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ctr Mat TSV'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_cttparcial',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ct.T.Parcial'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_cód_acervo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cód. Acervo'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_cód_servent',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cód. Servent'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_códúnico',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cód.Único'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_d_temisrg',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='D t.Emis.RG'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_data_admis',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Data Admis.'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_data_caged',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Data Caged'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_data_chegada',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Data Chegada'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_data_efeito',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Data Efeito'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_data_emissão',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Data Emissão'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_data_nasc',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Data Nasc.'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_ddd_celular',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='DDD Celular'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_ddd_telefone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='DDD Telefone'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_defi_esocial',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Defi eSocial'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_dep_ir',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dep. I.R.'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_depfgts',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='% Dep.Fgts'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_depsalfam',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dep.Sal.Fam.'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_desc_depto',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Desc. Depto'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_desc_mun_l',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Desc. Mun. L'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_desc_rem_var',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Desc Rem Var'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_descfuncao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Desc.Funcao'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_descrlograd',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descr.Lograd'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_dnaturaliza',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='D.Naturaliza'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_dt_afast_mol',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dt Afast Mol'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_dt_demissao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dt. Demissao'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_dt_efev_ret',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dt Efev Ret'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_dt_emis_pass',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dt Emis Pass'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_dt_ini_benef',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dt Ini Benef'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_dt_prim_cnh',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dt Prim CNH'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_dt_rec_incap',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dt Rec Incap'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_dt_term_cont',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dt Term Cont'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_dt_val_pass',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dt Val Pass'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_dtemisctps',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dt.Emis.CTPS'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_dtexped_ric',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dt.Exped RIC'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_dtexprne',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dt.Exp.RNE'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_dtopfgts',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dt.Op.FGTS'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_e_gestor',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='E Gestor?'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_email_altern',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Email Altern'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_email_princ',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Email Princ'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_emissor_pass',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Emissor Pass'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_emissor_ric',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Emissor RIC'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_endereço',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_envrecpgto',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Env.Rec.Pgto'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_est_civil',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Est. Civil'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_filho_bras',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Filho Bras.'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_folha',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Folha'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_horas_dia',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Horas Dia'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_hrs_insal',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Hrs. Insal.'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_hrs_mensais',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Hrs. Mensais'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_hrsperic',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Hrs.Peric.'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_hrssemanais',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Hrs.Semanais'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_id_procjud',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Id. Proc.Jud'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_incapacitado',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Incapacitado'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_item',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Item'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_jorvariavel',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Jor.Variavel'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_justificativ',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Justificativ'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_lei_anistia',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Lei Anistia'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_livro',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Livro'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_local_benef',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Local Benef.'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_mat_migração',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Mat Migração'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_mei',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='MEI'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_mens_sindica',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Mens Sindica'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_mot_admissa',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Mot. Admissa'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_multipinsal',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Multip.Insal'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_mun_loc',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Mun. Loc.'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_municipio',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Municipio'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_municpnasc',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Municp.Nasc.'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_nacionalid',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nacionalid.'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_naturalid_uf',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Naturalid UF'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_naturalizac',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Naturalizac.'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_nome_complet',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome complet'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_nome_mae',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Mae'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_nome_pai',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Pai'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_nome_social',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Social'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_noregistro',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='No.Registro'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_nr_cracha',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nr. Cracha'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_nrlogradouro',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='NrLogradouro'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_nrreservis',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nr.Reservis.'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_num_celular',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Num. Celular'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_num_insc_aut',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Num Insc Aut'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_num_pag_fech',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Num Pag Fech'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_num_passap',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Num. Passap.'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_numendereço',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Num.Endereço'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_numero_ric',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Numero RIC'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_número_rne',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Número RNE'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_org_emis_rg',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Org Emis RG'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_orgao_exp_rg',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Orgao exp RG'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_orgcl_dt_val',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='OrgCl Dt Val'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_orgcl_dtemis',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='OrgCl DtEmis'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_orgclemissor',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='OrgClEmissor'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_orgemisrne',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Org.Emis.RNE'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_orgemissor',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Org.Emissor'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_painel_fluxo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Painel Fluxo'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_país_res_ext',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='País Res Ext'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_per_fechado',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Per. Fechado'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_plsaúde',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Pl.Saúde'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_possui_insal',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Possui Insal'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_possui_per',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Possui Per.?'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_procfechado',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Proc.Fechado'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_procmenor_14',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ProcMenor 14'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_racacor',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Raca/Cor'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_receb_email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Receb E-Mail'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_reg_civil',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Reg. Civil'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_regra_apont',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Regra Apont.'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_resexterior',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Res.Exterior'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_rot_fechado',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Rot. Fechado'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_seqiniturn',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Seq.Ini.Turn'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_setor_resp',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Setor Resp'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_seção_eleit',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Seção Eleit.'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_sit_folha',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sit. Folha'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_substituto',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Substituto'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_série_cart',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Série Cart.'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_telefone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Telefone'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_tempo_resid',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tempo Resid.'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_termomatric',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Termo/Matric'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_tip_certid',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tip. Certid.'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_tipendereço',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tip.Endereço'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_tipo_admiss',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tipo Admiss.'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_tipo_cta_sal',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tipo Cta Sal'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_tipo_email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tipo E-Mail'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_tipo_justif',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tipo Justif.'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_tipo_livro',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tipo Livro'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_tipo_lograd',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tipo Lograd'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_tipo_pgto',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tipo Pgto.'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_titeleit',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tit.Eleit.'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_tp_previden',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tp Previden.'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_tp_regjtra',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tp Reg.J.Tra'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_tp_serv_aut',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tp Serv Aut'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_tpcontdeterm',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='TpContDeterm'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_tpconttrab',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tp.Cont.Trab'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_tpdeficien',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tp.Deficien'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_tpreinesoc',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tp.Rein.eSoc'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_turno_trab',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Turno Trab.'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_uf',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='UF'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_uf_cartprof',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='UF Cart.Prof'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_uf_do_rg',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='UF do RG'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_uf_loc',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Uf Loc.'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_uf_passaport',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='UF Passaport'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_uf_ric',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='UF RIC'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_usr_adm',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Usr Adm'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_venexamed',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ven.Exa.Med.'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_vinemprais',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Vin.Emp.RAIS'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ra_zona_eleit',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Zona Eleit'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='ra_bairro',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='ra_cep',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cep'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='ra_estado',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='ra_filial',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Filial'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='ra_mat',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Matricula'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='ra_nome',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='ra_pis',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='P.I.S.'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='ra_rg',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='R.G.'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='ra_sexo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sexo'),
        ),
    ]
