# Generated by Django 5.2.7 on 2025-10-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarquia', '0002_vaga_requisicaopessoal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requisicaopessoal',
            old_name='aprovado_por_coordenador',
            new_name='aprovado_por_gestor',
        ),
        migrations.RenameField(
            model_name='requisicaopessoal',
            old_name='aprovado_por_diretor',
            new_name='aprovado_por_rh',
        ),
        migrations.RenameField(
            model_name='requisicaopessoal',
            old_name='data_aprovacao_coordenador',
            new_name='data_aprovacao_gestor',
        ),
        migrations.RenameField(
            model_name='requisicaopessoal',
            old_name='data_aprovacao_diretor',
            new_name='data_aprovacao_rh',
        ),
        migrations.RemoveField(
            model_name='requisicaopessoal',
            name='aprovado_por_gerente',
        ),
        migrations.RemoveField(
            model_name='requisicaopessoal',
            name='aprovado_por_supervisor',
        ),
        migrations.RemoveField(
            model_name='requisicaopessoal',
            name='data_aprovacao_gerente',
        ),
        migrations.RemoveField(
            model_name='requisicaopessoal',
            name='data_aprovacao_supervisor',
        ),
        migrations.RemoveField(
            model_name='requisicaopessoal',
            name='observacoes_aprovador',
        ),
        migrations.AddField(
            model_name='requisicaopessoal',
            name='justificativa_edicao_rh',
            field=models.TextField(blank=True, help_text='Justificativa da edição feita pelo RH para o gestor revisar.', null=True),
        ),
        migrations.AddField(
            model_name='requisicaopessoal',
            name='observacao_rejeicao',
            field=models.TextField(blank=True, help_text='Motivo da rejeição final.', null=True),
        ),
        migrations.AlterField(
            model_name='requisicaopessoal',
            name='status',
            field=models.CharField(choices=[('pendente_gestor', 'Pendente Gestor/Coordenador'), ('pendente_rh', 'Pendente RH'), ('em_revisao_gestor', 'Em Revisão (Edição RH)'), ('aprovada', 'Aprovada'), ('rejeitada', 'Rejeitada'), ('cancelada', 'Cancelada')], max_length=30, verbose_name='Status da Requisição'),
        ),
    ]
