# Generated by Django 5.2.7 on 2025-10-29 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarquia', '0003_rename_aprovado_por_coordenador_requisicaopessoal_aprovado_por_gestor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimentacaoPessoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data da Solicitação')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('salario_atual', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salário Atual')),
                ('salario_proposto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salário Proposto')),
                ('tipo_movimentacao', models.CharField(choices=[('promocao', 'Promoção'), ('transferencia', 'Transferência'), ('aumento_salarial', 'Aumento Salarial'), ('reclassificacao', 'Reclassificação'), ('outro', 'Outro')], max_length=30, verbose_name='Tipo de Movimentação')),
                ('data_efetiva', models.DateField(verbose_name='Data Efetiva da Movimentação')),
                ('justificativa', models.TextField(verbose_name='Justificativa da Movimentação')),
                ('status', models.CharField(choices=[('pendente_gestor_proposto', 'Pendente Gestor Proposto'), ('pendente_gestor_atual', 'Pendente Gestor Atual'), ('pendente_rh', 'Pendente RH'), ('aprovada', 'Aprovada'), ('rejeitada', 'Rejeitada')], max_length=30, verbose_name='Status da Movimentação')),
                ('observacao_rejeicao', models.TextField(blank=True, help_text='Motivo da rejeição.', null=True)),
                ('data_aprovacao_gestor_proposto', models.DateTimeField(blank=True, null=True)),
                ('data_aprovacao_gestor_atual', models.DateTimeField(blank=True, null=True)),
                ('data_aprovacao_rh', models.DateTimeField(blank=True, null=True)),
                ('data_rejeicao', models.DateTimeField(blank=True, null=True)),
                ('aprovado_por_gestor_atual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='hierarquia.funcionario')),
                ('aprovado_por_gestor_proposto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='hierarquia.funcionario')),
                ('aprovado_por_rh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='hierarquia.funcionario')),
                ('aprovador_atual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mps_para_aprovar', to='hierarquia.funcionario', verbose_name='Próximo Aprovador')),
                ('cargo_atual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='hierarquia.cargo', verbose_name='Cargo Atual')),
                ('cargo_proposto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='hierarquia.cargo', verbose_name='Cargo Proposto')),
                ('funcionario_movido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='hierarquia.funcionario', verbose_name='Funcionário a ser Movido')),
                ('rejeitado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='hierarquia.funcionario')),
                ('setor_atual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='hierarquia.setor', verbose_name='Setor Atual')),
                ('setor_proposto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='hierarquia.setor', verbose_name='Setor Proposto')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mps_solicitadas', to='hierarquia.funcionario', verbose_name='Solicitante (ADM)')),
            ],
            options={
                'verbose_name': 'Movimentação Pessoal',
                'verbose_name_plural': 'Movimentações Pessoais',
                'ordering': ['-criado_em'],
            },
        ),
    ]
