# Generated by Django 5.2.7 on 2025-10-29 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarquia', '0004_movimentacaopessoal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimentacaopessoal',
            name='aprovado_por_gestor_atual',
        ),
        migrations.RemoveField(
            model_name='movimentacaopessoal',
            name='aprovado_por_gestor_proposto',
        ),
        migrations.RemoveField(
            model_name='movimentacaopessoal',
            name='aprovador_atual',
        ),
        migrations.RemoveField(
            model_name='movimentacaopessoal',
            name='tipo_movimentacao',
        ),
        migrations.AddField(
            model_name='movimentacaopessoal',
            name='aprovador_gestor_atual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mps_para_aprovar_atual', to='hierarquia.funcionario'),
        ),
        migrations.AddField(
            model_name='movimentacaopessoal',
            name='aprovador_gestor_proposto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mps_para_aprovar_proposto', to='hierarquia.funcionario'),
        ),
        migrations.AddField(
            model_name='movimentacaopessoal',
            name='aprovador_rh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mps_para_aprovar_rh', to='hierarquia.funcionario'),
        ),
        migrations.AddField(
            model_name='movimentacaopessoal',
            name='gestor_atual_aprovou',
            field=models.BooleanField(default=False, verbose_name='Gestor Atual Aprovou?'),
        ),
        migrations.AddField(
            model_name='movimentacaopessoal',
            name='gestor_proposto_aprovou',
            field=models.BooleanField(default=False, verbose_name='Gestor Proposto Aprovou?'),
        ),
        migrations.AlterField(
            model_name='movimentacaopessoal',
            name='aprovado_por_rh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mps_aprovadas_rh', to='hierarquia.funcionario'),
        ),
        migrations.AlterField(
            model_name='movimentacaopessoal',
            name='rejeitado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mps_rejeitadas', to='hierarquia.funcionario'),
        ),
        migrations.AlterField(
            model_name='movimentacaopessoal',
            name='status',
            field=models.CharField(choices=[('pendente_gestores', 'Pendente Gestores (Atual e Proposto)'), ('pendente_rh', 'Pendente RH'), ('aprovada', 'Aprovada'), ('rejeitada', 'Rejeitada')], default='pendente_gestores', max_length=30, verbose_name='Status da Movimentação'),
        ),
    ]
