# Generated by Django 5.2.7 on 2025-10-30 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarquia', '0005_remove_movimentacaopessoal_aprovado_por_gestor_atual_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequisicaoDesligamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data da Solicitação')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('data_admissao', models.DateField(blank=True, null=True, verbose_name='Data de Admissão')),
                ('tipo_desligamento', models.CharField(choices=[('empresa', 'Iniciativa da Empresa'), ('funcionario', 'Iniciativa do Funcionário')], max_length=20, verbose_name='Tipo de Desligamento')),
                ('motivo', models.CharField(choices=[('termino_contrato', 'Término de Contrato de Experiência'), ('reducao_quadro', 'Redução de Quadro'), ('baixo_desempenho', 'Baixo Desempenho'), ('justa_causa', 'Justa Causa'), ('pedido_demissao', 'Pedido de Demissão'), ('abandono_emprego', 'Abandono de Emprego'), ('aposentadoria', 'Aposentadoria'), ('falecimento', 'Falecimento'), ('outro', 'Outro (Especificar na Justificativa)')], max_length=30, verbose_name='Motivo')),
                ('data_prevista_desligamento', models.DateField(verbose_name='Data Prevista (Último dia)')),
                ('tipo_aviso', models.CharField(choices=[('trabalhado', 'Trabalhado'), ('indenizado', 'Indenizado'), ('dispensado', 'Dispensa de Cumprimento'), ('nao_se_aplica', 'Não se Aplica')], max_length=20, verbose_name='Tipo de Aviso Prévio')),
                ('havera_substituicao', models.BooleanField(default=False, verbose_name='Haverá Substituição?')),
                ('justificativa', models.TextField(verbose_name='Justificativa / Detalhes')),
                ('entrevista_realizada', models.BooleanField(default=False, verbose_name='Entrevista de Desligamento Realizada?')),
                ('data_entrevista', models.DateField(blank=True, null=True, verbose_name='Data da Entrevista')),
                ('status', models.CharField(choices=[('pendente_gestor', 'Pendente Gestor Imediato'), ('pendente_rh', 'Pendente RH'), ('aprovada', 'Aprovada (Desligamento Efetivado)'), ('rejeitada', 'Rejeitada')], max_length=30, verbose_name='Status da Requisição')),
                ('observacao_rejeicao', models.TextField(blank=True, help_text='Motivo da rejeição.', null=True)),
                ('data_aprovacao_gestor', models.DateTimeField(blank=True, null=True)),
                ('data_aprovacao_rh', models.DateTimeField(blank=True, null=True)),
                ('data_rejeicao', models.DateTimeField(blank=True, null=True)),
                ('aprovado_por_gestor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='hierarquia.funcionario')),
                ('aprovado_por_rh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='hierarquia.funcionario')),
                ('aprovador_atual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rds_para_aprovar', to='hierarquia.funcionario', verbose_name='Próximo Aprovador')),
                ('cargo_atual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='hierarquia.cargo', verbose_name='Cargo Atual')),
                ('funcionario_desligado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='desligamentos', to='hierarquia.funcionario', verbose_name='Funcionário a ser Desligado')),
                ('rejeitado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='hierarquia.funcionario')),
                ('setor_atual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='hierarquia.setor', verbose_name='Setor Atual')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rds_solicitadas', to='hierarquia.funcionario', verbose_name='Solicitante (ADM)')),
            ],
            options={
                'verbose_name': 'Requisição de Desligamento',
                'verbose_name_plural': 'Requisições de Desligamento',
                'ordering': ['-criado_em'],
            },
        ),
    ]
